GPU_id: '0'
adversary_list:
- 0
aggregate_all_layer: 1
alpha: 0.1
alpha_loss: 1.0
anticipate: 0
anticipate_gamma: 0.998
anticipate_local_epochs: 2
anticipate_lr: 0.01
anticipate_steps: 5
baseline: false
batch_norm_param_scale_weights: 1
batch_size: 64
clamp_value: 1.0
contrastive_loss_down_scale_weight: 1
contrastive_loss_ne_weight: 0
contrastive_loss_ps_weight: 0
contrastive_loss_scale_weight: 0.0
contrastive_loss_weight: 1
current_time: Jun.16_04.21.47
dataset: cifar10
decay: 0.0005
decay_contrastive: 0.0005
diff_privacy: false
diff_privacy_benign: false
diff_privacy_contrastive: false
dirichlet_alpha: 0.5
edge_case: 0
env: fl-running-18
environment_name: ppdl_experiment_cifar_pixel_pattern_12
epochs: 4000
eta: 0.1
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_load: false
fake_participants_save: false
folder_path: ./saved_models/vae-train-1
generator_epoch: 25
generator_lr: 0.003
global_model_scale_weight: 0
grad_cam: false
gradmask_ratio: 1.0
gumbel_threshold: 0.7
is_frozen_params: 1
is_frozen_params_contrastive: false
is_poison: true
label_flip_backdoor: false
log_interval: 10
lr: 0.001
lr_gamma: 0.005
lr_gamma_contrastive: 0.1
margin: 0.5
marks: green car baseline cifar10 1800 100 clients, lr=0.0001 when epochs >poison_epochs[-1]
mask_contrastive: 0
milestones:
- 3
- 5
milestones_conrtastive:
- 3
- 5
- 7
- 9
model_type: ResNet18
modify_poison: false
momentum: 0.9
momentum_contrastive: 0.9
new_model_scale_weights: 1
no_models: 10
noise_level: 0.01
norm_bound: 3
norm_clip: false
number_of_adversaries: 1
number_of_total_participants: 100
output_name: vae-train-1
params: utils/params_pixel_trigger_cifar10.yaml
pattern_diff: 0.0
pattern_type: 6
persistence_diff: 0.03
pixel_num: 5
pixel_pattern: true
poison_batch_len: 5
poison_decay: 0.005
poison_epochs:
- 1801
- 1802
- 1803
- 1804
- 1805
- 1806
- 1807
- 1808
- 1809
- 1810
- 1811
- 1812
- 1813
- 1814
- 1815
- 1816
- 1817
- 1818
- 1819
- 1820
- 1821
- 1822
- 1823
- 1824
- 1825
- 1826
- 1827
- 1828
- 1829
- 1830
- 1831
- 1832
- 1833
- 1834
- 1835
- 1836
- 1837
- 1838
- 1839
- 1840
- 1841
- 1842
- 1843
- 1844
- 1845
- 1846
- 1847
- 1848
- 1849
- 1850
poison_image_id: 2775
poison_image_id_2: 1605
poison_images:
- 561
- 389
- 874
- 1605
- 4528
- 9744
- 21422
- 19500
- 19165
- 22984
- 34287
- 34385
- 36005
- 37365
- 37533
- 38735
- 39824
- 40138
- 41336
- 41861
- 47026
- 48003
- 48030
- 49163
- 49588
poison_images_test:
- 38658
- 47001
- 3378
- 3678
- 32941
poison_label_swap: 9
poison_lr: 0.01
poison_lr_contrastive: 0.005
poison_momentum: 0.9
poison_step_lr: true
poison_step_lr_contrastive: true
poison_test_repeat: 1000
poison_type: wall
poisoned_number: 2
poisoning_per_batch: 1
poisoning_per_batch_contrastive: 1
poisoning_per_batch_high: 10
poisoning_per_batch_low: 0
random_compromise: false
regularize_batch: false
regularize_len: 14
replace_batchnorm: false
report_poison_loss: true
report_test_loss: true
report_train_loss: true
results_json: false
resumed_model: true
resumed_model_path: cifar/model_last.pt.tar.epoch_1800
retrain_no_times: 2
retrain_poison: 3
retrain_poison_contrastive: 10
retrain_poison_stage_3: 0
s_norm: 5
s_norm_contrastive: 5
sampling_dirichlet: true
save_grad_epochs:
- 100
save_model: true
save_on_epochs:
- 1000
- 1500
- 1800
- 1825
- 1850
- 1900
- 1950
- 2001
- 2019
- 2040
- 2100
- 2149
- 2200
- 2249
scale_partial_weight: false
scale_weight_mean: 1.2
scale_weight_var: 3
scale_weights: 1
semantic_backdoor: false
size_of_secret_dataset: 25
size_of_secret_dataset_label_flip: 500
start_epoch: 1800
target_lr: 0.2
test_batch_size: 1000
test_forgetting: false
tied_params: []
track_clusters: false
track_distance: false
trigger_size: 4
triplet_loss_scale_weight: 2.0
type: image
